body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Bitwarden clients repo! As an open source project, Bitwarden is built in part by you—the community! To learn how to submit a pull request for consideration, please review [https://contributing.bitwarden.com/](https://contributing.bitwarden.com/) and share your proposal in the [Community PR Proposals](https://github.com/orgs/bitwarden/discussions/categories/community-pr-proposals) category. To keep discussion on topic, posts that do not include a specific PR proposal (for a code contribution you wish to develop) will be removed. For feature requests and community discussion, please visit https://community.bitwarden.com/
  - type: textarea
    attributes:
      label: Code Contribution Proposal
      description: "Please share details about the PR you would like to work on. Be sure to include a description of your proposed contribution, screenshots, and links to any relevant [feature requests](https://community.bitwarden.com/c/feature-requests/5/none). This helps get feedback from the community and Bitwarden team members before you start writing code"
    validations:
      required: true
